export const ADD_TO_CART = "ADD_TO_CART";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const LOAD_CURRENT_ITEM = "LOAD_CURRENT_ITEM";

export const DELETE_FROM_CART = "DELETE_FROM_CART";

export const DELETE_FROM_PROFILE = "DELETE_FROM_PROFILE";

export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST";

export const UPDATE_QTY = "UPDATE_QTY";

export const EMPTY_CART = "EMPTY_CART";

export const EMPTY_WISH = "EMPTY_WISH";

export const APPLY_SEARCH = "APPLY_SEARCH";

export const ADD_PROFILE_DATA = "ADD_PROFILE_DATA";
